figure(1),imshow(bk1);
title('Input Video');
pause(0.01);
figure(1),imshow(bk2);
title('Input Video');
pause(0.01);
figure(1),imshow(bk3);
title('Input Video');
pause(0.01);
figure(1),imshow(bk4);
title('Input Video');
pause(0.01);
figure(1),imshow(bk5);
title('Input Video');
pause(0.01);
figure(1),imshow(bk6);
title('Input Video');
pause(0.01);
figure(1),imshow(bk7);
title('Input Video');
pause(0.01);
figure(1),imshow(bk8);
title('Input Video');
pause(0.01);
figure(1),imshow(bk9);
title('Input Video');
pause(0.01);
figure(1),imshow(bk10);
title('Input Video');
pause(0.01);
figure(1),imshow(bk11);
title('Input Video');
pause(0.01);
figure(1),imshow(bk12);
title('Input Video');
pause(0.01);
figure(1),imshow(bk13);
title('Input Video');
pause(0.01);
figure(1),imshow(bk14);
title('Input Video');
pause(0.01);
figure(1),imshow(bk15);
title('Input Video');
pause(0.01);
figure(1),imshow(bk16);
title('Input Video');
pause(0.01);
figure(1),imshow(bk17);
title('Input Video');
pause(0.01);
figure(1),imshow(bk18);
title('Input Video');
pause(0.01);
figure(1),imshow(bk19);
title('Input Video');
pause(0.01);
figure(1),imshow(bk20);
title('Input Video');
pause(0.01);
figure(1),imshow(bk21);
title('Input Video');
pause(0.01);
figure(1),imshow(bk22);
title('Input Video');
pause(0.01);
figure(1),imshow(bk23);
title('Input Video');
pause(0.01);
figure(1),imshow(bk24);
title('Input Video');
pause(0.01);
figure(1),imshow(bk25);
title('Input Video');
pause(0.01);
figure(1),imshow(bk26);
title('Input Video');
pause(0.01);
figure(1),imshow(bk27);
title('Input Video');
pause(0.01);
figure(1),imshow(bk28);
title('Input Video');
pause(0.01);
figure(1),imshow(bk29);
title('Input Video');
pause(0.01);
figure(1),imshow(bk30);
title('Input Video');
pause(0.01);
figure(1),imshow(bk31);
title('Input Video');
pause(0.01);
figure(1),imshow(bk32);
title('Input Video');
figure(1),imshow(bk33);
title('Input Video');
pause(0.01);
figure(1),imshow(bk34);
title('Input Video');
pause(0.01);
figure(1),imshow(bk35);
title('Input Video');
pause(0.01);
figure(1),imshow(bk36);
title('Input Video');
pause(0.01);
figure(1),imshow(bk37);
title('Input Video');
pause(0.01);
figure(1),imshow(bk38);
title('Input Video');
pause(0.01);
figure(1),imshow(bk39);
title('Input Video');
pause(0.01);
figure(1),imshow(bk40);
title('Input Video');
pause(0.01);
figure(1),imshow(bk41);
title('Input Video');
pause(0.01);
figure(1),imshow(bk42);
title('Input Video');
pause(0.01);
figure(1),imshow(bk43);
title('Input Video');
pause(0.01);
figure(1),imshow(bk44);
title('Input Video');
pause(0.01);
figure(1),imshow(bk45);
title('Input Video');
pause(0.01);
figure(1),imshow(bk46);
title('Input Video');
pause(0.01);
figure(1),imshow(bk47);
title('Input Video');
pause(0.01);
figure(1),imshow(bk48);
title('Input Video');
pause(0.01);
figure(1),imshow(bk49);
title('Input Video');
pause(0.01);
figure(1),imshow(bk50);
title('Input Video');
pause(0.01);
