figure(1),imshow(crk1);
title('Input Video');
pause(0.01);
figure(1),imshow(crk2);
title('Input Video');
pause(0.01);
figure(1),imshow(crk3);
title('Input Video');
pause(0.01);
figure(1),imshow(crk4);
title('Input Video');
pause(0.01);
figure(1),imshow(crk5);
title('Input Video');
pause(0.01);
figure(1),imshow(crk6);
title('Input Video');
pause(0.01);
figure(1),imshow(crk7);
title('Input Video');
pause(0.01);
figure(1),imshow(crk8);
title('Input Video');
pause(0.01);
figure(1),imshow(crk9);
title('Input Video');
pause(0.01);
figure(1),imshow(crk10);
title('Input Video');
pause(0.01);
figure(1),imshow(crk11);
title('Input Video');
pause(0.01);
figure(1),imshow(crk12);
title('Input Video');
pause(0.01);
figure(1),imshow(crk13);
title('Input Video');
pause(0.01);
figure(1),imshow(crk14);
title('Input Video');
pause(0.01);
figure(1),imshow(crk15);
title('Input Video');
pause(0.01);
figure(1),imshow(crk16);
title('Input Video');
pause(0.01);
figure(1),imshow(crk17);
title('Input Video');
pause(0.01);
figure(1),imshow(crk18);
title('Input Video');
pause(0.01);
figure(1),imshow(crk19);
title('Input Video');
pause(0.01);
figure(1),imshow(crk20);
title('Input Video');
pause(0.01);
figure(1),imshow(crk21);
title('Input Video');
pause(0.01);
figure(1),imshow(crk22);
title('Input Video');
pause(0.01);
figure(1),imshow(crk23);
title('Input Video');
pause(0.01);
figure(1),imshow(crk24);
title('Input Video');
pause(0.01);
figure(1),imshow(crk25);
title('Input Video');
pause(0.01);
figure(1),imshow(crk26);
title('Input Video');
pause(0.01);
figure(1),imshow(crk27);
title('Input Video');
pause(0.01);
figure(1),imshow(crk28);
title('Input Video');
pause(0.01);
figure(1),imshow(crk29);
title('Input Video');
pause(0.01);
figure(1),imshow(crk30);
title('Input Video');
pause(0.01);
figure(1),imshow(crk31);
title('Input Video');
pause(0.01);
figure(1),imshow(crk32);
title('Input Video');
figure(1),imshow(crk33);
title('Input Video');
pause(0.01);
figure(1),imshow(crk34);
title('Input Video');
pause(0.01);
figure(1),imshow(crk35);
title('Input Video');
pause(0.01);
figure(1),imshow(crk36);
title('Input Video');
pause(0.01);
figure(1),imshow(crk37);
title('Input Video');
pause(0.01);
figure(1),imshow(crk38);
title('Input Video');
pause(0.01);
figure(1),imshow(crk39);
title('Input Video');
pause(0.01);
figure(1),imshow(crk40);
title('Input Video');
pause(0.01);
figure(1),imshow(crk41);
title('Input Video');
pause(0.01);
figure(1),imshow(crk42);
title('Input Video');
pause(0.01);
figure(1),imshow(crk43);
title('Input Video');
pause(0.01);
figure(1),imshow(crk44);
title('Input Video');
pause(0.01);
figure(1),imshow(crk45);
title('Input Video');
pause(0.01);
figure(1),imshow(crk46);
title('Input Video');
pause(0.01);
figure(1),imshow(crk47);
title('Input Video');
pause(0.01);
figure(1),imshow(crk48);
title('Input Video');
pause(0.01);
figure(1),imshow(crk49);
title('Input Video');
pause(0.01);
figure(1),imshow(crk50);
title('Input Video');
pause(0.01);
figure(1),imshow(crk51);
title('Input Video');
pause(0.01);
figure(1),imshow(crk52);
title('Input Video');
pause(0.01);
figure(1),imshow(crk53);
title('Input Video');
pause(0.01);
figure(1),imshow(crk54);
title('Input Video');
pause(0.01);
figure(1),imshow(crk55);
title('Input Video');
pause(0.01);
figure(1),imshow(crk56);
title('Input Video');
pause(0.01);
figure(1),imshow(crk57);
title('Input Video');
pause(0.01);
figure(1),imshow(crk58);
title('Input Video');
pause(0.01);
figure(1),imshow(crk59);
title('Input Video');
pause(0.01);
figure(1),imshow(crk60);
title('Input Video');
pause(0.01);
figure(1),imshow(crk61);
title('Input Video');
pause(0.01);
figure(1),imshow(crk62);
title('Input Video');
pause(0.01);
figure(1),imshow(crk63);
title('Input Video');
pause(0.01);
figure(1),imshow(crk64);
title('Input Video');
pause(0.01);
figure(1),imshow(crk65);
title('Input Video');
pause(0.01);
figure(1),imshow(crk66);
title('Input Video');
pause(0.01);
figure(1),imshow(crk67);
title('Input Video');
pause(0.01);
figure(1),imshow(crk68);
title('Input Video');
pause(0.01);
figure(1),imshow(crk69);
title('Input Video');
pause(0.01);
figure(1),imshow(crk70);
title('Input Video');
pause(0.01);
figure(1),imshow(crk71);
title('Input Video');
pause(0.01);
figure(1),imshow(crk72);
title('Input Video');
pause(0.01);
figure(1),imshow(crk73);
title('Input Video');
pause(0.01);
figure(1),imshow(crk74);
title('Input Video');
pause(0.01);
figure(1),imshow(crk75);
title('Input Video');
pause(0.01);
figure(1),imshow(crk76);
title('Input Video');
pause(0.01);
figure(1),imshow(crk77);
title('Input Video');
pause(0.01);
figure(1),imshow(crk78);
title('Input Video');
pause(0.01);
figure(1),imshow(crk79);
title('Input Video');
pause(0.01);
figure(1),imshow(crk80);
title('Input Video');
pause(0.01);
figure(1),imshow(crk81);
title('Input Video');
pause(0.01);
figure(1),imshow(crk82);
title('Input Video');
pause(0.01);
figure(1),imshow(crk83);
title('Input Video');
pause(0.01);
figure(1),imshow(crk84);
title('Input Video');
pause(0.01);
figure(1),imshow(crk85);
title('Input Video');
pause(0.01);
figure(1),imshow(crk86);
title('Input Video');
pause(0.01);
figure(1),imshow(crk87);
title('Input Video');
pause(0.01);
figure(1),imshow(crk88);
title('Input Video');
pause(0.01);
figure(1),imshow(crk89);
title('Input Video');
pause(0.01);
figure(1),imshow(crk90);
title('Input Video');
pause(0.01);
figure(1),imshow(crk91);
title('Input Video');
pause(0.01);
figure(1),imshow(crk92);
title('Input Video');
pause(0.01);
figure(1),imshow(crk93);
title('Input Video');
pause(0.01);
figure(1),imshow(crk94);
title('Input Video');
pause(0.01);
figure(1),imshow(crk95);
title('Input Video');
pause(0.01);
figure(1),imshow(crk96);
title('Input Video');
pause(0.01);
figure(1),imshow(crk97);
title('Input Video');
pause(0.01);
figure(1),imshow(crk98);
title('Input Video');
pause(0.01);
figure(1),imshow(crk99);
title('Input Video');
pause(0.01);
figure(1),imshow(crk100);
title('Input Video');
pause(0.01);

