figure(1),imshow(de1);
title('Input Video');
pause(0.01);
figure(1),imshow(de2);
title('Input Video');
pause(0.01);
figure(1),imshow(de3);
title('Input Video');
pause(0.01);
figure(1),imshow(de4);
title('Input Video');
pause(0.01);
figure(1),imshow(de5);
title('Input Video');
pause(0.01);
figure(1),imshow(de6);
title('Input Video');
pause(0.01);
figure(1),imshow(de7);
title('Input Video');
pause(0.01);
figure(1),imshow(de8);
title('Input Video');
pause(0.01);
figure(1),imshow(de9);
title('Input Video');
pause(0.01);
figure(1),imshow(de10);
title('Input Video');
pause(0.01);
figure(1),imshow(de11);
title('Input Video');
pause(0.01);
figure(1),imshow(de12);
title('Input Video');
pause(0.01);
figure(1),imshow(de13);
title('Input Video');
pause(0.01);
figure(1),imshow(de14);
title('Input Video');
pause(0.01);
figure(1),imshow(de15);
title('Input Video');
pause(0.01);
figure(1),imshow(de16);
title('Input Video');
pause(0.01);
figure(1),imshow(de17);
title('Input Video');
pause(0.01);
figure(1),imshow(de18);
title('Input Video');
pause(0.01);
figure(1),imshow(de19);
title('Input Video');
pause(0.01);
figure(1),imshow(de20);
title('Input Video');
pause(0.01);
figure(1),imshow(de21);
title('Input Video');
pause(0.01);
figure(1),imshow(de22);
title('Input Video');
pause(0.01);
figure(1),imshow(de23);
title('Input Video');
pause(0.01);
figure(1),imshow(de24);
title('Input Video');
pause(0.01);
figure(1),imshow(de25);
title('Input Video');
pause(0.01);
figure(1),imshow(de26);
title('Input Video');
pause(0.01);
figure(1),imshow(de27);
title('Input Video');
pause(0.01);
figure(1),imshow(de28);
title('Input Video');
pause(0.01);
figure(1),imshow(de29);
title('Input Video');
pause(0.01);
figure(1),imshow(de30);
title('Input Video');
pause(0.01);
figure(1),imshow(de31);
title('Input Video');
pause(0.01);
figure(1),imshow(de32);
title('Input Video');
figure(1),imshow(de33);
title('Input Video');
pause(0.01);
figure(1),imshow(de34);
title('Input Video');
pause(0.01);
figure(1),imshow(de35);
title('Input Video');
pause(0.01);
figure(1),imshow(de36);
title('Input Video');
pause(0.01);
figure(1),imshow(de37);
title('Input Video');
pause(0.01);
figure(1),imshow(de38);
title('Input Video');
pause(0.01);
figure(1),imshow(de39);
title('Input Video');
pause(0.01);
figure(1),imshow(de40);
title('Input Video');
pause(0.01);
figure(1),imshow(de41);
title('Input Video');
pause(0.01);
figure(1),imshow(de42);
title('Input Video');
pause(0.01);
figure(1),imshow(de43);
title('Input Video');
pause(0.01);
figure(1),imshow(de44);
title('Input Video');
pause(0.01);
figure(1),imshow(de45);
title('Input Video');
pause(0.01);
figure(1),imshow(de46);
title('Input Video');
pause(0.01);
figure(1),imshow(de47);
title('Input Video');
pause(0.01);
figure(1),imshow(de48);
title('Input Video');
pause(0.01);
figure(1),imshow(de49);
title('Input Video');
pause(0.01);
figure(1),imshow(de50);
title('Input Video');
pause(0.01);
figure(1),imshow(de51);
title('Input Video');
pause(0.01);
figure(1),imshow(de52);
title('Input Video');
pause(0.01);
figure(1),imshow(de53);
title('Input Video');
pause(0.01);
figure(1),imshow(de54);
title('Input Video');
pause(0.01);
figure(1),imshow(de55);
title('Input Video');
pause(0.01);
figure(1),imshow(de56);
title('Input Video');
pause(0.01);
figure(1),imshow(de57);
title('Input Video');
pause(0.01);
figure(1),imshow(de58);
title('Input Video');
pause(0.01);
figure(1),imshow(de59);
title('Input Video');
pause(0.01);
figure(1),imshow(de60);
title('Input Video');
pause(0.01);
figure(1),imshow(de61);
title('Input Video');
pause(0.01);
figure(1),imshow(de62);
title('Input Video');
pause(0.01);
figure(1),imshow(de63);
title('Input Video');
pause(0.01);
figure(1),imshow(de64);
title('Input Video');
pause(0.01);
figure(1),imshow(de65);
title('Input Video');
pause(0.01);
figure(1),imshow(de66);
title('Input Video');
pause(0.01);
figure(1),imshow(de67);
title('Input Video');
pause(0.01);
figure(1),imshow(de68);
title('Input Video');
pause(0.01);
figure(1),imshow(de69);
title('Input Video');
pause(0.01);
figure(1),imshow(de70);
title('Input Video');
pause(0.01);
figure(1),imshow(de71);
title('Input Video');
pause(0.01);
figure(1),imshow(de72);
title('Input Video');
pause(0.01);
figure(1),imshow(de73);
title('Input Video');
pause(0.01);
figure(1),imshow(de74);
title('Input Video');
pause(0.01);
figure(1),imshow(de75);
title('Input Video');
pause(0.01);
figure(1),imshow(de76);
title('Input Video');
pause(0.01);
figure(1),imshow(de77);
title('Input Video');
pause(0.01);
figure(1),imshow(de78);
title('Input Video');
pause(0.01);
figure(1),imshow(de79);
title('Input Video');
pause(0.01);
figure(1),imshow(de80);
title('Input Video');
pause(0.01);
figure(1),imshow(de81);
title('Input Video');
pause(0.01);
figure(1),imshow(de82);
title('Input Video');
pause(0.01);
figure(1),imshow(de83);
title('Input Video');
pause(0.01);
figure(1),imshow(de84);
title('Input Video');
pause(0.01);
figure(1),imshow(de85);
title('Input Video');
pause(0.01);
figure(1),imshow(de86);
title('Input Video');
pause(0.01);
figure(1),imshow(de87);
title('Input Video');
pause(0.01);
figure(1),imshow(de88);
title('Input Video');
pause(0.01);
figure(1),imshow(de89);
title('Input Video');
pause(0.01);
figure(1),imshow(de90);
title('Input Video');
pause(0.01);
figure(1),imshow(de91);
title('Input Video');
pause(0.01);
figure(1),imshow(de92);
title('Input Video');
pause(0.01);
figure(1),imshow(de93);
title('Input Video');
pause(0.01);
figure(1),imshow(de94);
title('Input Video');
pause(0.01);
figure(1),imshow(de95);
title('Input Video');
pause(0.01);
figure(1),imshow(de96);
title('Input Video');
pause(0.01);
figure(1),imshow(de97);
title('Input Video');
pause(0.01);
figure(1),imshow(de98);
title('Input Video');
pause(0.01);
figure(1),imshow(de99);
title('Input Video');
pause(0.01);
figure(1),imshow(de101);
title('Input Video');
pause(0.01);

