figure(1),imshow(b1);
title('Input Video');
pause(0.1);
figure(1),imshow(b2);
title('Input Video');
pause(0.1);
figure(1),imshow(b3);
title('Input Video');
pause(0.1);
figure(1),imshow(b4);
title('Input Video');
pause(0.1);
figure(1),imshow(b5);
title('Input Video');
pause(0.1);
figure(1),imshow(b6);
title('Input Video');
pause(0.1);
figure(1),imshow(b7);
title('Input Video');
pause(0.1);
figure(1),imshow(b8);
title('Input Video');
pause(0.1);
figure(1),imshow(b9);
title('Input Video');
pause(0.1);
figure(1),imshow(b10);
title('Input Video');
pause(0.1);
figure(1),imshow(b11);
title('Input Video');
pause(0.1);
figure(1),imshow(b12);
title('Input Video');
pause(0.1);
figure(1),imshow(b13);
title('Input Video');
pause(0.1);
figure(1),imshow(b14);
title('Input Video');
pause(0.1);
figure(1),imshow(b15);
title('Input Video');
pause(0.1);
figure(1),imshow(b16);
title('Input Video');
pause(0.1);
figure(1),imshow(b17);
title('Input Video');
pause(0.1);
figure(1),imshow(b18);
title('Input Video');
pause(0.1);
figure(1),imshow(b19);
title('Input Video');
pause(0.1);
figure(1),imshow(b20);
title('Input Video');
pause(0.1);
figure(1),imshow(b21);
title('Input Video');
pause(0.1);
figure(1),imshow(b22);
title('Input Video');
pause(0.1);
figure(1),imshow(b23);
title('Input Video');
pause(0.1);
figure(1),imshow(b24);
title('Input Video');
pause(0.1);
figure(1),imshow(b25);
title('Input Video');
pause(0.1);
figure(1),imshow(b26);
title('Input Video');
pause(0.1);
figure(1),imshow(b27);
title('Input Video');
pause(0.1);
figure(1),imshow(b28);
title('Input Video');
pause(0.1);
figure(1),imshow(b29);
title('Input Video');
pause(0.1);
figure(1),imshow(b30);
title('Input Video');
pause(0.1);
figure(1),imshow(b31);
title('Input Video');
pause(0.1);
figure(1),imshow(b32);
title('Input Video');