figure(1),imshow(d1);
title('Input Video');
pause(0.1);
figure(1),imshow(d2);
title('Input Video');
pause(0.1);
figure(1),imshow(d3);
title('Input Video');
pause(0.1);
figure(1),imshow(d4);
title('Input Video');
pause(0.1);
figure(1),imshow(d5);
title('Input Video');
pause(0.1);
figure(1),imshow(d6);
title('Input Video');
pause(0.1);
figure(1),imshow(d7);
title('Input Video');
pause(0.1);
figure(1),imshow(d8);
title('Input Video');
pause(0.1);
figure(1),imshow(d9);
title('Input Video');
pause(0.1);
figure(1),imshow(d10);
title('Input Video');
pause(0.1);
figure(1),imshow(d11);
title('Input Video');
pause(0.1);
figure(1),imshow(d12);
title('Input Video');
pause(0.1);
figure(1),imshow(d13);
title('Input Video');
pause(0.1);
figure(1),imshow(d14);
title('Input Video');
pause(0.1);
figure(1),imshow(d15);
title('Input Video');
pause(0.1);
figure(1),imshow(d16);
title('Input Video');
pause(0.1);
figure(1),imshow(d17);
title('Input Video');
pause(0.1);
figure(1),imshow(d18);
title('Input Video');
pause(0.1);
figure(1),imshow(d19);
title('Input Video');
pause(0.1);
figure(1),imshow(d20);
title('Input Video');
pause(0.1);
figure(1),imshow(d21);
title('Input Video');
pause(0.1);
figure(1),imshow(d22);
title('Input Video');
pause(0.1);
figure(1),imshow(d23);
title('Input Video');
pause(0.1);
figure(1),imshow(d24);
title('Input Video');
pause(0.1);
figure(1),imshow(d25);
title('Input Video');
pause(0.1);
figure(1),imshow(d26);
title('Input Video');
pause(0.1);
figure(1),imshow(d27);
title('Input Video');
pause(0.1);
figure(1),imshow(d28);
title('Input Video');
pause(0.1);
figure(1),imshow(d29);
title('Input Video');
pause(0.1);
figure(1),imshow(d30);
title('Input Video');
pause(0.1);
figure(1),imshow(d31);
title('Input Video');
pause(0.1);
figure(1),imshow(d32);
title('Input Video');
pause(0.1);
figure(1),imshow(d33);
title('Input Video');
pause(0.1);
figure(1),imshow(d34);
title('Input Video');
pause(0.1);
figure(1),imshow(d35);
title('Input Video');
pause(0.1);
figure(1),imshow(d36);
title('Input Video');
pause(0.1);
figure(1),imshow(d37);
title('Input Video');
pause(0.1);
figure(1),imshow(d38);
title('Input Video');
pause(0.1);
figure(1),imshow(d39);
title('Input Video');
pause(0.1);
figure(1),imshow(d40);
title('Input Video');
pause(0.1);
figure(1),imshow(d41);
title('Input Video');
pause(0.1);
figure(1),imshow(d42);
title('Input Video');
pause(0.1);
figure(1),imshow(d43);
title('Input Video');
pause(0.1);
figure(1),imshow(d44);
title('Input Video');
pause(0.1);
figure(1),imshow(d45);
title('Input Video');
pause(0.1);
figure(1),imshow(d46);
title('Input Video');
pause(0.1);
figure(1),imshow(d47);
title('Input Video');
pause(0.1);
figure(1),imshow(d48);
title('Input Video');
pause(0.1);
figure(1),imshow(d49);
title('Input Video');
pause(0.1);
figure(1),imshow(d50);
title('Input Video');
pause(0.1);
figure(1),imshow(d51);
title('Input Video');
pause(0.1);
figure(1),imshow(d52);
title('Input Video');
pause(0.1);
figure(1),imshow(d53);
title('Input Video');
pause(0.1);
figure(1),imshow(d54);
title('Input Video');
pause(0.1);
figure(1),imshow(d55);
title('Input Video');
pause(0.1);
figure(1),imshow(d56);
title('Input Video');
pause(0.1);
figure(1),imshow(d57);
title('Input Video');
pause(0.1);
figure(1),imshow(d58);
title('Input Video');
pause(0.1);
figure(1),imshow(d59);
title('Input Video');
pause(0.1);
figure(1),imshow(d60);
title('Input Video');
pause(0.1);
figure(1),imshow(d61);
title('Input Video');
pause(0.1);
figure(1),imshow(d62);
title('Input Video');
pause(0.1);
figure(1),imshow(d63);
title('Input Video');
pause(0.1);
figure(1),imshow(d64);
title('Input Video');
pause(0.1);
figure(1),imshow(d65);
title('Input Video');
pause(0.1);
figure(1),imshow(d66);
title('Input Video');
pause(0.1);
figure(1),imshow(d67);
title('Input Video');
pause(0.1);
figure(1),imshow(d68);
title('Input Video');
pause(0.1);
figure(1),imshow(d69);
title('Input Video');
pause(0.1);
figure(1),imshow(d70);
title('Input Video');
pause(0.1);
figure(1),imshow(d71);
title('Input Video');
pause(0.1);
figure(1),imshow(d72);
title('Input Video');
pause(0.1);
figure(1),imshow(d73);
title('Input Video');
pause(0.1);
figure(1),imshow(d74);
title('Input Video');
pause(0.1);
figure(1),imshow(d75);
title('Input Video');
pause(0.1);
figure(1),imshow(d76);
title('Input Video');
pause(0.1);
figure(1),imshow(d77);
title('Input Video');
pause(0.1);
figure(1),imshow(d78);
title('Input Video');
pause(0.1);
figure(1),imshow(d79);
title('Input Video');
pause(0.1);
figure(1),imshow(d80);
title('Input Video');
pause(0.1);
figure(1),imshow(d81);
title('Input Video');
pause(0.1);
figure(1),imshow(d82);
title('Input Video');
pause(0.1);
figure(1),imshow(d83);
title('Input Video');
pause(0.1);