figure(1),imshow(h1);
title('Input Video');
pause(0.1);
figure(1),imshow(h2);
title('Input Video');
pause(0.1);
figure(1),imshow(h3);
title('Input Video');
pause(0.1);
figure(1),imshow(h4);
title('Input Video');
pause(0.1);
figure(1),imshow(h5);
title('Input Video');
pause(0.1);
figure(1),imshow(h6);
title('Input Video');
pause(0.1);
figure(1),imshow(h7);
title('Input Video');
pause(0.1);
figure(1),imshow(h8);
title('Input Video');
pause(0.1);
figure(1),imshow(h9);
title('Input Video');
pause(0.1);
figure(1),imshow(h10);
title('Input Video');
pause(0.1);
figure(1),imshow(h11);
title('Input Video');
pause(0.1);
figure(1),imshow(h12);
title('Input Video');
pause(0.1);
figure(1),imshow(h13);
title('Input Video');
pause(0.1);
figure(1),imshow(h14);
title('Input Video');
pause(0.1);
figure(1),imshow(h15);
title('Input Video');
pause(0.1);
figure(1),imshow(h16);
title('Input Video');
pause(0.1);
figure(1),imshow(h17);
title('Input Video');
pause(0.1);
figure(1),imshow(h18);
title('Input Video');
pause(0.1);
figure(1),imshow(h19);
title('Input Video');
pause(0.1);
figure(1),imshow(h20);
title('Input Video');
pause(0.1);
figure(1),imshow(h21);
title('Input Video');
pause(0.1);
figure(1),imshow(h22);
title('Input Video');
pause(0.1);
figure(1),imshow(h23);
title('Input Video');
pause(0.1);
figure(1),imshow(h24);
title('Input Video');
pause(0.1);
figure(1),imshow(h25);
title('Input Video');
pause(0.1);
figure(1),imshow(h26);
title('Input Video');
pause(0.1);
figure(1),imshow(h27);
title('Input Video');
pause(0.1);
figure(1),imshow(h28);
title('Input Video');
pause(0.1);
figure(1),imshow(h29);
title('Input Video');
pause(0.1);
figure(1),imshow(h30);
title('Input Video');
pause(0.1);
figure(1),imshow(h31);
title('Input Video');
pause(0.1);
figure(1),imshow(h32);
title('Input Video');
pause(0.1);
figure(1),imshow(h33);
title('Input Video');
pause(0.1);
figure(1),imshow(h34);
title('Input Video');
pause(0.1);
figure(1),imshow(h35);
title('Input Video');
pause(0.1);
figure(1),imshow(h36);
title('Input Video');
pause(0.1);
figure(1),imshow(h37);
title('Input Video');
pause(0.1);
figure(1),imshow(h38);
title('Input Video');
pause(0.1);
figure(1),imshow(h39);
title('Input Video');
pause(0.1);
figure(1),imshow(h40);
title('Input Video');
pause(0.1);
figure(1),imshow(h41);
title('Input Video');
pause(0.1);
figure(1),imshow(h42);
title('Input Video');
pause(0.1);
figure(1),imshow(h43);
title('Input Video');
pause(0.1);
figure(1),imshow(h44);
title('Input Video');
pause(0.1);
figure(1),imshow(h45);
title('Input Video');
pause(0.1);
figure(1),imshow(h46);
title('Input Video');
pause(0.1);
figure(1),imshow(h47);
title('Input Video');
pause(0.1);
figure(1),imshow(h48);
title('Input Video');
pause(0.1);
figure(1),imshow(h49);
title('Input Video');
pause(0.1);
figure(1),imshow(h50);
title('Input Video');
pause(0.1);
figure(1),imshow(h51);
title('Input Video');
pause(0.1);
figure(1),imshow(h52);
title('Input Video');
pause(0.1);
figure(1),imshow(h53);
title('Input Video');
pause(0.1);
figure(1),imshow(h54);
title('Input Video');
pause(0.1);
figure(1),imshow(h55);
title('Input Video');
pause(0.1);
figure(1),imshow(h56);
title('Input Video');
pause(0.1);
figure(1),imshow(h57);
title('Input Video');
pause(0.1);
figure(1),imshow(h58);
title('Input Video');
pause(0.1);
figure(1),imshow(h59);
title('Input Video');
pause(0.1);
figure(1),imshow(h60);
title('Input Video');
pause(0.1);
figure(1),imshow(h61);
title('Input Video');
pause(0.1);
figure(1),imshow(h62);
title('Input Video');
pause(0.1);
figure(1),imshow(h63);
title('Input Video');
pause(0.1);
figure(1),imshow(h64);
title('Input Video');
pause(0.1);
figure(1),imshow(h65);
title('Input Video');
pause(0.1);
figure(1),imshow(h66);
title('Input Video');
pause(0.1);
figure(1),imshow(h67);
title('Input Video');
pause(0.1);
figure(1),imshow(h68);
title('Input Video');
pause(0.1);
figure(1),imshow(h69);
title('Input Video');
pause(0.1);
figure(1),imshow(h70);
title('Input Video');
pause(0.1);
figure(1),imshow(h71);
title('Input Video');
pause(0.1);
figure(1),imshow(h72);
title('Input Video');
pause(0.1);
figure(1),imshow(h73);
title('Input Video');
pause(0.1);
figure(1),imshow(h74);
title('Input Video');
pause(0.1);
figure(1),imshow(h75);
title('Input Video');
pause(0.1);
figure(1),imshow(h76);
title('Input Video');
pause(0.1);
figure(1),imshow(h77);
title('Input Video');
pause(0.1);
figure(1),imshow(h78);
title('Input Video');
pause(0.1);
figure(1),imshow(h79);
title('Input Video');
pause(0.1);
figure(1),imshow(h80);
title('Input Video');
pause(0.1);
figure(1),imshow(h81);
title('Input Video');
pause(0.1);
