figure(1),imshow(t1);
title('Input Video');
pause(0.1);
figure(1),imshow(t2);
title('Input Video');
pause(0.1);
figure(1),imshow(t3);
title('Input Video');
pause(0.1);
figure(1),imshow(t4);
title('Input Video');
pause(0.1);
figure(1),imshow(t5);
title('Input Video');
pause(0.1);
figure(1),imshow(t6);
title('Input Video');
pause(0.1);
figure(1),imshow(t7);
title('Input Video');
pause(0.1);
figure(1),imshow(t8);
title('Input Video');
pause(0.1);
figure(1),imshow(t9);
title('Input Video');
pause(0.1);
figure(1),imshow(t10);
title('Input Video');
pause(0.1);
figure(1),imshow(t11);
title('Input Video');
pause(0.1);
figure(1),imshow(t12);
title('Input Video');
pause(0.1);
figure(1),imshow(t13);
title('Input Video');
pause(0.1);
figure(1),imshow(t14);
title('Input Video');
pause(0.1);
figure(1),imshow(t15);
title('Input Video');
pause(0.1);
figure(1),imshow(t16);
title('Input Video');
pause(0.1);
figure(1),imshow(t17);
title('Input Video');
pause(0.1);
figure(1),imshow(t18);
title('Input Video');
pause(0.1);
figure(1),imshow(t19);
title('Input Video');
pause(0.1);
figure(1),imshow(t20);
title('Input Video');
pause(0.1);
figure(1),imshow(t21);
title('Input Video');
pause(0.1);
figure(1),imshow(t22);
title('Input Video');
pause(0.1);
figure(1),imshow(t23);
title('Input Video');
pause(0.1);
figure(1),imshow(t24);
title('Input Video');
pause(0.1);
figure(1),imshow(t25);
title('Input Video');
pause(0.1);
figure(1),imshow(t26);
title('Input Video');
pause(0.1);
figure(1),imshow(t27);
title('Input Video');
pause(0.1);
figure(1),imshow(t28);
title('Input Video');
pause(0.1);
figure(1),imshow(t29);
title('Input Video');
pause(0.1);
figure(1),imshow(t30);
title('Input Video');
pause(0.1);
figure(1),imshow(t31);
title('Input Video');
pause(0.1);
figure(1),imshow(t32);
title('Input Video');
pause(0.1);
figure(1),imshow(t33);
title('Input Video');
pause(0.1);
figure(1),imshow(t34);
title('Input Video');
pause(0.1);
figure(1),imshow(t35);
title('Input Video');
pause(0.1);
figure(1),imshow(t36);
title('Input Video');
pause(0.1);
figure(1),imshow(t37);
title('Input Video');
pause(0.1);
figure(1),imshow(t38);
title('Input Video');
pause(0.1);
figure(1),imshow(t39);
title('Input Video');
pause(0.1);
figure(1),imshow(t40);
title('Input Video');
pause(0.1);
figure(1),imshow(t41);
title('Input Video');
pause(0.1);
figure(1),imshow(t42);
title('Input Video');
pause(0.1);
figure(1),imshow(t43);
title('Input Video');
pause(0.1);
figure(1),imshow(t44);
title('Input Video');
pause(0.1);
figure(1),imshow(t45);
title('Input Video');
pause(0.1);
figure(1),imshow(t46);
title('Input Video');
pause(0.1);
figure(1),imshow(t47);
title('Input Video');
pause(0.1);
figure(1),imshow(t48);
title('Input Video');
pause(0.1);
figure(1),imshow(t49);
title('Input Video');
pause(0.1);
figure(1),imshow(t50);
title('Input Video');
pause(0.1);
figure(1),imshow(t51);
title('Input Video');
pause(0.1);
figure(1),imshow(t52);
title('Input Video');
pause(0.1);
figure(1),imshow(t53);
title('Input Video');
pause(0.1);
figure(1),imshow(t54);
title('Input Video');
pause(0.1);
figure(1),imshow(t55);
title('Input Video');
pause(0.1);
figure(1),imshow(t56);
title('Input Video');
pause(0.1);
figure(1),imshow(t57);
title('Input Video');
pause(0.1);
figure(1),imshow(t58);
title('Input Video');
pause(0.1);
figure(1),imshow(t59);
title('Input Video');
pause(0.1);
figure(1),imshow(t60);
title('Input Video');
pause(0.1);
