figure(1),imshow(swim1);
title('Input Video');
pause(0.01);
figure(1),imshow(swim2);
title('Input Video');
pause(0.01);
figure(1),imshow(swim3);
title('Input Video');
pause(0.01);
figure(1),imshow(swim4);
title('Input Video');
pause(0.01);
figure(1),imshow(swim5);
title('Input Video');
pause(0.01);
figure(1),imshow(swim6);
title('Input Video');
pause(0.01);
figure(1),imshow(swim7);
title('Input Video');
pause(0.01);
figure(1),imshow(swim8);
title('Input Video');
pause(0.01);
figure(1),imshow(swim9);
title('Input Video');
pause(0.01);
figure(1),imshow(swim10);
title('Input Video');
pause(0.01);
figure(1),imshow(swim11);
title('Input Video');
pause(0.01);
figure(1),imshow(swim12);
title('Input Video');
pause(0.01);
figure(1),imshow(swim13);
title('Input Video');
pause(0.01);
figure(1),imshow(swim14);
title('Input Video');
pause(0.01);
figure(1),imshow(swim15);
title('Input Video');
pause(0.01);
figure(1),imshow(swim16);
title('Input Video');
pause(0.01);
figure(1),imshow(swim17);
title('Input Video');
pause(0.01);
figure(1),imshow(swim18);
title('Input Video');
pause(0.01);
figure(1),imshow(swim19);
title('Input Video');
pause(0.01);
figure(1),imshow(swim20);
title('Input Video');
pause(0.01);
figure(1),imshow(swim21);
title('Input Video');
pause(0.01);
figure(1),imshow(swim22);
title('Input Video');
pause(0.01);
figure(1),imshow(swim23);
title('Input Video');
pause(0.01);
figure(1),imshow(swim24);
title('Input Video');
pause(0.01);
figure(1),imshow(swim25);
title('Input Video');
pause(0.01);
figure(1),imshow(swim26);
title('Input Video');
pause(0.01);
figure(1),imshow(swim27);
title('Input Video');
pause(0.01);
figure(1),imshow(swim28);
title('Input Video');
pause(0.01);
figure(1),imshow(swim29);
title('Input Video');
pause(0.01);
figure(1),imshow(swim30);
title('Input Video');
pause(0.01);
figure(1),imshow(swim31);
title('Input Video');
pause(0.01);
figure(1),imshow(swim32);
title('Input Video');
figure(1),imshow(swim33);
title('Input Video');
pause(0.01);
figure(1),imshow(swim34);
title('Input Video');
pause(0.01);
figure(1),imshow(swim35);
title('Input Video');
pause(0.01);
figure(1),imshow(swim36);
title('Input Video');
pause(0.01);
figure(1),imshow(swim37);
title('Input Video');
pause(0.01);
figure(1),imshow(swim38);
title('Input Video');
pause(0.01);
figure(1),imshow(swim39);
title('Input Video');
pause(0.01);
figure(1),imshow(swim40);
title('Input Video');
pause(0.01);
figure(1),imshow(swim41);
title('Input Video');
pause(0.01);
figure(1),imshow(swim42);
title('Input Video');
pause(0.01);
figure(1),imshow(swim43);
title('Input Video');
pause(0.01);
figure(1),imshow(swim44);
title('Input Video');
pause(0.01);
figure(1),imshow(swim45);
title('Input Video');
pause(0.01);
figure(1),imshow(swim46);
title('Input Video');
pause(0.01);
figure(1),imshow(swim47);
title('Input Video');
pause(0.01);
figure(1),imshow(swim48);
title('Input Video');
pause(0.01);
figure(1),imshow(swim49);
title('Input Video');
pause(0.01);
figure(1),imshow(swim50);
title('Input Video');
pause(0.01);
figure(1),imshow(swim51);
title('Input Video');
pause(0.01);
figure(1),imshow(swim52);
title('Input Video');
pause(0.01);
figure(1),imshow(swim53);
title('Input Video');
pause(0.01);
figure(1),imshow(swim54);
title('Input Video');
pause(0.01);
figure(1),imshow(swim55);
title('Input Video');
pause(0.01);
figure(1),imshow(swim56);
title('Input Video');
pause(0.01);
figure(1),imshow(swim57);
title('Input Video');
pause(0.01);
figure(1),imshow(swim58);
title('Input Video');
pause(0.01);
figure(1),imshow(swim59);
title('Input Video');
pause(0.01);
figure(1),imshow(swim60);
title('Input Video');
pause(0.01);
figure(1),imshow(swim61);
title('Input Video');
pause(0.01);
figure(1),imshow(swim62);
title('Input Video');
pause(0.01);
figure(1),imshow(swim63);
title('Input Video');
pause(0.01);
figure(1),imshow(swim64);
title('Input Video');
pause(0.01);
figure(1),imshow(swim65);
title('Input Video');
pause(0.01);
figure(1),imshow(swim66);
title('Input Video');
pause(0.01);
figure(1),imshow(swim67);
title('Input Video');
pause(0.01);
figure(1),imshow(swim68);
title('Input Video');
pause(0.01);
figure(1),imshow(swim69);
title('Input Video');
pause(0.01);
figure(1),imshow(swim70);
title('Input Video');
pause(0.01);
figure(1),imshow(swim71);
title('Input Video');
pause(0.01);
figure(1),imshow(swim72);
title('Input Video');
pause(0.01);
figure(1),imshow(swim73);
title('Input Video');
pause(0.01);
figure(1),imshow(swim74);
title('Input Video');
pause(0.01);
figure(1),imshow(swim75);
title('Input Video');
pause(0.01);
figure(1),imshow(swim76);
title('Input Video');
pause(0.01);
figure(1),imshow(swim77);
title('Input Video');
pause(0.01);
figure(1),imshow(swim78);
title('Input Video');
pause(0.01);
figure(1),imshow(swim79);
title('Input Video');
pause(0.01);
figure(1),imshow(swim80);
title('Input Video');
pause(0.01);
figure(1),imshow(swim81);
title('Input Video');
pause(0.01);
figure(1),imshow(swim82);
title('Input Video');
pause(0.01);
figure(1),imshow(swim83);
title('Input Video');
pause(0.01);
figure(1),imshow(swim84);
title('Input Video');
pause(0.01);
figure(1),imshow(swim85);
title('Input Video');
pause(0.01);
figure(1),imshow(swim86);
title('Input Video');
pause(0.01);
figure(1),imshow(swim87);
title('Input Video');
pause(0.01);
figure(1),imshow(swim88);
title('Input Video');
pause(0.01);
figure(1),imshow(swim89);
title('Input Video');
pause(0.01);
figure(1),imshow(swim90);
title('Input Video');
pause(0.01);
figure(1),imshow(swim91);
title('Input Video');
pause(0.01);
figure(1),imshow(swim92);
title('Input Video');
pause(0.01);
figure(1),imshow(swim93);
title('Input Video');
pause(0.01);
figure(1),imshow(swim94);
title('Input Video');
pause(0.01);
figure(1),imshow(swim95);
title('Input Video');
pause(0.01);
figure(1),imshow(swim96);
title('Input Video');
pause(0.01);
figure(1),imshow(swim97);
title('Input Video');
pause(0.01);
figure(1),imshow(swim98);
title('Input Video');
pause(0.01);
figure(1),imshow(swim99);
title('Input Video');
pause(0.01);
figure(1),imshow(swim100);
title('Input Video');
pause(0.01);

