figure(1),imshow(swi1);
title('Input Video');
pause(0.01);
figure(1),imshow(swi2);
title('Input Video');
pause(0.01);
figure(1),imshow(swi3);
title('Input Video');
pause(0.01);
figure(1),imshow(swi4);
title('Input Video');
pause(0.01);
figure(1),imshow(swi5);
title('Input Video');
pause(0.01);
figure(1),imshow(swi6);
title('Input Video');
pause(0.01);
figure(1),imshow(swi7);
title('Input Video');
pause(0.01);
figure(1),imshow(swi8);
title('Input Video');
pause(0.01);
figure(1),imshow(swi9);
title('Input Video');
pause(0.01);
figure(1),imshow(swi10);
title('Input Video');
pause(0.01);
figure(1),imshow(swi11);
title('Input Video');
pause(0.01);
figure(1),imshow(swi12);
title('Input Video');
pause(0.01);
figure(1),imshow(swi13);
title('Input Video');
pause(0.01);
figure(1),imshow(swi14);
title('Input Video');
pause(0.01);
figure(1),imshow(swi15);
title('Input Video');
pause(0.01);
figure(1),imshow(swi16);
title('Input Video');
pause(0.01);
figure(1),imshow(swi17);
title('Input Video');
pause(0.01);
figure(1),imshow(swi18);
title('Input Video');
pause(0.01);
figure(1),imshow(swi19);
title('Input Video');
pause(0.01);
figure(1),imshow(swi20);
title('Input Video');
pause(0.01);
figure(1),imshow(swi21);
title('Input Video');
pause(0.01);
figure(1),imshow(swi22);
title('Input Video');
pause(0.01);
figure(1),imshow(swi23);
title('Input Video');
pause(0.01);
figure(1),imshow(swi24);
title('Input Video');
pause(0.01);
figure(1),imshow(swi25);
title('Input Video');
pause(0.01);
figure(1),imshow(swi26);
title('Input Video');
pause(0.01);
figure(1),imshow(swi27);
title('Input Video');
pause(0.01);
figure(1),imshow(swi28);
title('Input Video');
pause(0.01);
figure(1),imshow(swi29);
title('Input Video');
pause(0.01);
figure(1),imshow(swi30);
title('Input Video');
pause(0.01);
figure(1),imshow(swi31);
title('Input Video');
pause(0.01);
figure(1),imshow(swi32);
title('Input Video');
figure(1),imshow(swi33);
title('Input Video');
pause(0.01);
figure(1),imshow(swi34);
title('Input Video');
pause(0.01);
figure(1),imshow(swi35);
title('Input Video');
pause(0.01);
figure(1),imshow(swi36);
title('Input Video');
pause(0.01);
figure(1),imshow(swi37);
title('Input Video');
pause(0.01);
figure(1),imshow(swi38);
title('Input Video');
pause(0.01);
figure(1),imshow(swi39);
title('Input Video');
pause(0.01);
figure(1),imshow(swi40);
title('Input Video');
pause(0.01);
figure(1),imshow(swi41);
title('Input Video');
pause(0.01);
figure(1),imshow(swi42);
title('Input Video');
pause(0.01);
figure(1),imshow(swi43);
title('Input Video');
pause(0.01);
figure(1),imshow(swi44);
title('Input Video');
pause(0.01);
figure(1),imshow(swi45);
title('Input Video');
pause(0.01);
figure(1),imshow(swi46);
title('Input Video');
pause(0.01);
figure(1),imshow(swi47);
title('Input Video');
pause(0.01);
figure(1),imshow(swi48);
title('Input Video');
pause(0.01);
figure(1),imshow(swi49);
title('Input Video');
pause(0.01);
figure(1),imshow(swi50);
title('Input Video');
pause(0.01);
figure(1),imshow(swi51);
title('Input Video');
pause(0.01);
figure(1),imshow(swi52);
title('Input Video');
pause(0.01);
figure(1),imshow(swi53);
title('Input Video');
pause(0.01);
figure(1),imshow(swi54);
title('Input Video');
pause(0.01);
figure(1),imshow(swi55);
title('Input Video');
pause(0.01);
figure(1),imshow(swi56);
title('Input Video');
pause(0.01);
figure(1),imshow(swi57);
title('Input Video');
pause(0.01);
figure(1),imshow(swi58);
title('Input Video');
pause(0.01);
figure(1),imshow(swi59);
title('Input Video');
pause(0.01);
figure(1),imshow(swi60);
title('Input Video');
pause(0.01);
figure(1),imshow(swi61);
title('Input Video');
pause(0.01);
figure(1),imshow(swi62);
title('Input Video');
pause(0.01);
figure(1),imshow(swi63);
title('Input Video');
pause(0.01);
figure(1),imshow(swi64);
title('Input Video');
pause(0.01);
figure(1),imshow(swi65);
title('Input Video');
pause(0.01);
figure(1),imshow(swi66);
title('Input Video');
pause(0.01);
figure(1),imshow(swi67);
title('Input Video');
pause(0.01);
figure(1),imshow(swi68);
title('Input Video');
pause(0.01);
figure(1),imshow(swi69);
title('Input Video');
pause(0.01);
figure(1),imshow(swi70);
title('Input Video');
pause(0.01);
figure(1),imshow(swi71);
title('Input Video');
pause(0.01);
figure(1),imshow(swi72);
title('Input Video');
pause(0.01);
figure(1),imshow(swi73);
title('Input Video');
pause(0.01);
figure(1),imshow(swi74);
title('Input Video');
pause(0.01);
figure(1),imshow(swi75);
title('Input Video');
pause(0.01);
figure(1),imshow(swi76);
title('Input Video');
pause(0.01);
figure(1),imshow(swi77);
title('Input Video');
pause(0.01);
figure(1),imshow(swi78);
title('Input Video');
pause(0.01);
figure(1),imshow(swi79);
title('Input Video');
pause(0.01);
figure(1),imshow(swi80);
title('Input Video');
pause(0.01);
figure(1),imshow(swi81);
title('Input Video');
pause(0.01);
figure(1),imshow(swi82);
title('Input Video');
pause(0.01);
figure(1),imshow(swi83);
title('Input Video');
pause(0.01);
figure(1),imshow(swi84);
title('Input Video');
pause(0.01);
figure(1),imshow(swi85);
title('Input Video');
pause(0.01);
figure(1),imshow(swi86);
title('Input Video');
pause(0.01);
figure(1),imshow(swi87);
title('Input Video');
pause(0.01);
figure(1),imshow(swi88);
title('Input Video');
pause(0.01);
figure(1),imshow(swi89);
title('Input Video');
pause(0.01);
figure(1),imshow(swi90);
title('Input Video');
pause(0.01);
figure(1),imshow(swi91);
title('Input Video');
pause(0.01);
figure(1),imshow(swi92);
title('Input Video');
pause(0.01);
figure(1),imshow(swi93);
title('Input Video');
pause(0.01);
figure(1),imshow(swi94);
title('Input Video');
pause(0.01);
figure(1),imshow(swi95);
title('Input Video');
pause(0.01);
figure(1),imshow(swi96);
title('Input Video');
pause(0.01);
figure(1),imshow(swi97);
title('Input Video');
pause(0.01);
figure(1),imshow(swi98);
title('Input Video');
pause(0.01);
figure(1),imshow(swi99);
title('Input Video');
pause(0.01);
figure(1),imshow(swi100);
title('Input Video');
pause(0.01);

