figure(1),imshow(te1);
title('Input Video');
pause(0.1);
figure(1),imshow(te2);
title('Input Video');
pause(0.1);
figure(1),imshow(te3);
title('Input Video');
pause(0.1);
figure(1),imshow(te4);
title('Input Video');
pause(0.1);
figure(1),imshow(te5);
title('Input Video');
pause(0.1);
figure(1),imshow(te6);
title('Input Video');
pause(0.1);
figure(1),imshow(te7);
title('Input Video');
pause(0.1);
figure(1),imshow(te8);
title('Input Video');
pause(0.1);
figure(1),imshow(te9);
title('Input Video');
pause(0.1);
figure(1),imshow(te10);
title('Input Video');
pause(0.1);
figure(1),imshow(te11);
title('Input Video');
pause(0.1);
figure(1),imshow(te12);
title('Input Video');
pause(0.1);
figure(1),imshow(te13);
title('Input Video');
pause(0.1);
figure(1),imshow(te14);
title('Input Video');
pause(0.1);
figure(1),imshow(te15);
title('Input Video');
pause(0.1);
figure(1),imshow(te16);
title('Input Video');
pause(0.1);
figure(1),imshow(te17);
title('Input Video');
pause(0.1);
figure(1),imshow(te18);
title('Input Video');
pause(0.1);
figure(1),imshow(te19);
title('Input Video');
pause(0.1);
figure(1),imshow(te20);
title('Input Video');
pause(0.1);
figure(1),imshow(te21);
title('Input Video');
pause(0.1);
figure(1),imshow(te22);
title('Input Video');
pause(0.1);
figure(1),imshow(te23);
title('Input Video');
pause(0.1);
figure(1),imshow(te24);
title('Input Video');
pause(0.1);
figure(1),imshow(te25);
title('Input Video');
pause(0.1);
figure(1),imshow(te26);
title('Input Video');
pause(0.1);
figure(1),imshow(te27);
title('Input Video');
pause(0.1);
figure(1),imshow(te28);
title('Input Video');
pause(0.1);
figure(1),imshow(te29);
title('Input Video');
pause(0.1);
figure(1),imshow(te30);
title('Input Video');
pause(0.1);
figure(1),imshow(te31);
title('Input Video');
pause(0.1);
figure(1),imshow(te32);
title('Input Video');
figure(1),imshow(te33);
title('Input Video');
pause(0.1);
figure(1),imshow(te34);
title('Input Video');
pause(0.1);
figure(1),imshow(te35);
title('Input Video');
pause(0.1);
figure(1),imshow(te36);
title('Input Video');
pause(0.1);
figure(1),imshow(te37);
title('Input Video');
pause(0.1);
figure(1),imshow(te38);
title('Input Video');
pause(0.1);
figure(1),imshow(te39);
title('Input Video');
pause(0.1);
figure(1),imshow(te40);
title('Input Video');
pause(0.1);
figure(1),imshow(te41);
title('Input Video');
pause(0.1);
figure(1),imshow(te42);
title('Input Video');
pause(0.1);
figure(1),imshow(te43);
title('Input Video');
pause(0.1);
figure(1),imshow(te44);
title('Input Video');
pause(0.1);
figure(1),imshow(te45);
title('Input Video');
pause(0.1);
figure(1),imshow(te46);
title('Input Video');
pause(0.1);
figure(1),imshow(te47);
title('Input Video');
pause(0.1);
figure(1),imshow(te48);
title('Input Video');
pause(0.1);
figure(1),imshow(te49);
title('Input Video');
pause(0.1);
figure(1),imshow(te50);
title('Input Video');
pause(0.1);
