figure(1),imshow(weig1);
title('Input Video');
pause(0.1);
figure(1),imshow(weig2);
title('Input Video');
pause(0.1);
figure(1),imshow(weig3);
title('Input Video');
pause(0.1);
figure(1),imshow(weig4);
title('Input Video');
pause(0.1);
figure(1),imshow(weig5);
title('Input Video');
pause(0.1);
figure(1),imshow(weig6);
title('Input Video');
pause(0.1);
figure(1),imshow(weig7);
title('Input Video');
pause(0.1);
figure(1),imshow(weig8);
title('Input Video');
pause(0.1);
figure(1),imshow(weig9);
title('Input Video');
pause(0.1);
figure(1),imshow(weig10);
title('Input Video');
pause(0.1);
figure(1),imshow(weig11);
title('Input Video');
pause(0.1);
figure(1),imshow(weig12);
title('Input Video');
pause(0.1);
figure(1),imshow(weig13);
title('Input Video');
pause(0.1);
figure(1),imshow(weig14);
title('Input Video');
pause(0.1);
figure(1),imshow(weig15);
title('Input Video');
pause(0.1);
figure(1),imshow(weig16);
title('Input Video');
pause(0.1);
figure(1),imshow(weig17);
title('Input Video');
pause(0.1);
figure(1),imshow(weig18);
title('Input Video');
pause(0.1);
figure(1),imshow(weig19);
title('Input Video');
pause(0.1);
figure(1),imshow(weig20);
title('Input Video');
pause(0.1);
figure(1),imshow(weig21);
title('Input Video');
pause(0.1);
figure(1),imshow(weig22);
title('Input Video');
pause(0.1);
figure(1),imshow(weig23);
title('Input Video');
pause(0.1);
figure(1),imshow(weig24);
title('Input Video');
pause(0.1);
figure(1),imshow(weig25);
title('Input Video');
pause(0.1);
figure(1),imshow(weig26);
title('Input Video');
pause(0.1);
figure(1),imshow(weig27);
title('Input Video');
pause(0.1);
figure(1),imshow(weig28);
title('Input Video');
pause(0.1);
figure(1),imshow(weig29);
title('Input Video');
pause(0.1);
figure(1),imshow(weig30);
title('Input Video');
pause(0.1);
figure(1),imshow(weig31);
title('Input Video');
pause(0.1);
figure(1),imshow(weig32);
title('Input Video');
figure(1),imshow(weig33);
title('Input Video');
pause(0.1);
figure(1),imshow(weig34);
title('Input Video');
pause(0.1);
figure(1),imshow(weig35);
title('Input Video');
pause(0.1);
figure(1),imshow(weig36);
title('Input Video');
pause(0.1);
figure(1),imshow(weig37);
title('Input Video');
pause(0.1);
figure(1),imshow(weig38);
title('Input Video');
pause(0.1);
figure(1),imshow(weig39);
title('Input Video');
pause(0.1);
figure(1),imshow(weig40);
title('Input Video');
pause(0.1);
figure(1),imshow(weig41);
title('Input Video');
pause(0.1);
figure(1),imshow(weig42);
title('Input Video');
pause(0.1);
figure(1),imshow(weig43);
title('Input Video');
pause(0.1);
figure(1),imshow(weig44);
title('Input Video');
pause(0.1);
figure(1),imshow(weig45);
title('Input Video');
pause(0.1);
figure(1),imshow(weig46);
title('Input Video');
pause(0.1);
figure(1),imshow(weig47);
title('Input Video');
pause(0.1);
figure(1),imshow(weig48);
title('Input Video');
pause(0.1);
figure(1),imshow(weig49);
title('Input Video');
pause(0.1);
figure(1),imshow(weig50);
title('Input Video');
pause(0.1);
